### ISSUE TITLE
wasm size. maybe tinygo works now ?

### ISSUE THREAD

**Issue by gedw99** [mlctrez/mlctrez.github.io#1]
hey

1.42 MB encoded
5.08 MB decoded

still pretty big. any idea if tong works with go.app yet ? there is a good chance it works now as tinygo is slowly getting there.

**Comment by mlctrez** [comment]
What is "tong" ?

**Comment by gedw99** [comment]
sorry I was too tired - was a long session yesterday.

I meant to ask if we can compile go-app and nats.go with tinygo yet ?

**Comment by gedw99** [comment]
seems tinygo does not like it

tinygo version
tinygo version 0.31.2 darwin/arm64 (using go version go1.22.2 and LLVM version 17.0.1)

```sh
# github.com/maxence-charriere/go-app/v10/pkg/app
../../../../../../../../../../../pkg/mod/github.com/maxence-charriere/go-app/v10@v10.0.0-20240312064243-fd8d583dcdfa/pkg/app/node.go:784:13: v.Equal undefined (type reflect.Value has no field or method Equal)
../../../../../../../../../../../pkg/mod/github.com/maxence-charriere/go-app/v10@v10.0.0-20240312064243-fd8d583dcdfa/pkg/app/node.go:789:14: v.Equal undefined (type reflect.Value has no field or method Equal)
```

**Comment by mlctrez** [comment]
Yep that's the issue that I saw when I tried to use it last.  tinygo support for that reflect.Value Equal method

**Comment by gedw99** [comment]
I was hoping for v10 it might have been mitigated :)
